### ISSUE TITLE
Barcode not valid in iOS

### ISSUE THREAD

**Issue by Destronom** [thecodework/two-factor-authentication#47]
Hello, I have found an issue with Google Authenticator (iOS), with Android it works well:

The base32EncodedString Function in TwoFactorAuthenticationController.php should be min. length of 10 and not be dependent on the config('2fa-config.number_of_digits') value. Otherwise the base32 Function will pad with  "=" at the end of the string. It turns out, that Google Authenticator (iOS) doesn't accept "=" chars in Barcode URL. 

Source: https://stackoverflow.com/questions/29173288/google-authenticator-on-apple-devices-certain-secrets-are-not-valid

**Comment by imrealashu** [comment]
@Destronom The `2fa-config.number_of_digits` isn't the number of secret string which is being base32 encoded. Rather it denotes the number of passcode digits will be shown on the Google Authenticator or Authy clients.
Note: Google Authenticator supports only 6 digit of passcode. If you prefer changing it to more complex 8 digit passcode I'd suggest using Authy client.
Speaking about the padded "=" string at the end of the string then it's resolved now. The later versions (`>=0.1.7`) of this package would store `provisioned_uri` in the db instead of only base32encoded string.

**Comment by Destronom** [comment]
Thank you, I will check this out!
